apiVersion: apps/v1
kind: Deployment
metadata:
    name: jenkins
spec:
    replicas: 1
    selector:
        matchLabels:
            app: jenkins
    template:
        metadata:
            labels:
                app: jenkins
        spec:
            containers:
                - name: jenkins
                  image: myjenkins:latest
                  ports:
                      - name: http-port
                        containerPort: 8080
                      - name: jnlp-port
                        containerPort: 50000
                  volumeMounts:
                      - name: jenkins-vol
                        mountPath: /var/jenkins_vol
                      - name: docker-sock-volume
                        mountPath: "/var/run/docker.sock"
                  imagePullPolicy: Never
            volumes:
                - name: jenkins-vol
                  emptyDir: {}
                - name: docker-sock-volume
                  hostPath:
                      path: /var/run/docker.sock
